# Use uma imagem base do Node.js com Alpine Linux
FROM node:14-alpine

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos de configuração do pacote Node.js
COPY package.json package-lock.json /app/

# Copie o arquivo principal da aplicação
COPY server.js /app/

# Copie os arquivos estáticos da aplicação
COPY public /shell/public

# Instale as dependências do projeto
RUN npm install

# Copie o restante do código da aplicação, exceto o diretório "dist" se necessário
COPY src/ ./src/

# Exponha a porta necessária para a sua aplicação
EXPOSE 3003

# Comando padrão para iniciar a aplicação
CMD ["npm", "start"]
