# Use uma imagem base do Node.js com Alpine Linux
FROM node:14-alpine

# Diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos de configuração do pacote Node.js
COPY package.json package-lock.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante do código da aplicação, exceto o diretório "dist"
COPY src/ ./src/

# Exponha a porta necessária para a sua aplicação
EXPOSE 3000

# Comando padrão para iniciar a aplicação
CMD ["npm", "start"]
