version: '3.8'
services:
  bff:
    build: ./bff
    ports:
      - '3000:3000'
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  mf_drawer:
    build: ./mf_drawer
    ports:
      - '3001:3001'
    depends_on:
      - bff

  mf_videos:
    build: ./mf_videos
    ports:
      - '3002:3002'
    depends_on:
      - bff

  shell:
    build: ./shell
    ports:
      - '3003:3003'
    depends_on:
      - mf_drawer
      - mf_videos
